apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: github-nginx
  name: github-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-nginx
  template:
    metadata:
      labels:
        app: gh-nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - name: http
          containerPort: 80       
        resources:
          limits:
            cpu: "0.5"
            memory: "100Mi"
          requests:
            cpu: "0.3"   
            memory: "60Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: github-nginx-svc
  labels:
    app: github-nginx
spec:
  type: ClusterIP
  selector:
    app: github-nginx
  ports:
    - name: web
      port: 80
      targetPort: http
